Стили элементов, Resources
veselv2010/NowPlaying pull request #67
Opened 2020-05-06 11:09 UTC by veselv2010

2020-05-07 06:57 UTC, moetelo requested changes

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/MainWindow.xaml
> +    <!--Opacity="0.95"-->
уберём коммент?

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/PlayingTrack/PlayingTrackControl.xaml
> +                       FontFamily="/NowPlaying.Wpf;component/Resources/Font/#Montserrat"/>
а возможно где-то глобально в впф задать шрифт?
ты несколько раз написал `FontFamily=*fontname*`, это странно

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/PlayingTrack/PlayingTrackControl.xaml
> +                       FontFamily="/NowPlaying.Wpf;component/Resources/Font/#Montserrat"/>
https://stackoverflow.com/questions/3145511/how-to-set-the-default-font-for-a-wpf-application
у меня есть подозорение, что чтобы задать шрифт всему приложению, нужно задать шрифт для `MainWindow`

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/MainWindow.xaml
> +        Title="NowPlaying RUI"
`NowPlaying` же!

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/NpcWorkSwitch.xaml
> +    <Viewbox>
Убрал здесь `Viewbox`, получил точно такой же результат

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/NpcWorkSwitch.xaml
> +    <Viewbox>
Что не так? Для чего это?
Может, уберём?

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/Header/HeaderBlock.xaml
> +        <buttons:CrossButton Grid.Column="4" MouseLeftButtonDown="CloseButton_MouseLeftButtonDown" Height="Auto" Padding="5,15" Width="Auto"/>
```xaml
<buttons:LineButton Grid.Column="3"
                    Height="Auto" Width="Auto" Padding="5,15" />

<buttons:CrossButton Grid.Column="4" MouseLeftButtonDown="CloseButton_MouseLeftButtonDown"
                     Height="Auto" Width="Auto" Padding="5,15" />
```

давай вот так отформатируем!
если тебе по пути

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/NpcWorkSwitch.xaml
> +    <Viewbox>
Я так понял, ты решил многие юзерконтролы обернуть `Viewbox`, чтобы их сжимать и разжимать можно было.
Может, будем оборачивать только те, которые действительно необходимо сжимать?

Например, в случае `ToggleSwitch` это абсолютно логично!
В случае крестика тоже вполне (может где-то понадобиться крестик)

А такие контролы, которые просто являются частями окна, ну здесь ни к чему `Viewbox`.
(среди них: `NpcWorkSwitch`, `HeaderBlock`)
Такие контролы не реюзабельны, они сделаны для того, чтобы разбить код `MainWindow` немного.

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/Common/Toggle/ToggleSwitch.xaml.cs
> +        static readonly SolidColorBrush On = new SolidColorBrush(Color.FromRgb(29, 185, 84));
он же другой расцветки должен быть в случае свитчера `тёмная-светлая тема`
 
сможем придумать, как передавать в `тогглсвитч` кастомные цвета извне?

2020-05-07 06:57 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/Common/Toggle/ToggleSwitch.xaml.cs
> +        static readonly SolidColorBrush On = new SolidColorBrush(Color.FromRgb(29, 185, 84));
желательно передавать через хамл конечно и не через вьюмодель

2020-05-11 15:37 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/NpcWorkSwitch.xaml
> +             xmlns:common="clr-namespace:NowPlaying.Wpf.Controls.Common"
согласен

2020-05-11 16:15 UTC, veselv2010 commented on NowPlaying.Wpf/Controls/NpcWorkSwitch.xaml
> +             xmlns:common="clr-namespace:NowPlaying.Wpf.Controls.Common"
what did he mean by this

2020-05-12 10:24 UTC, moetelo submitted a review, later dismissed

2020-05-12 10:47 UTC, moetelo requested changes

2020-05-12 10:47 UTC, Shifu462 commented on NowPlaying.Wpf/NowPlaying.Wpf.csproj
> +    <BootstrapperEnabled>true</BootstrapperEnabled>
это чё за поебень

2020-05-12 10:47 UTC, Shifu462 commented on NowPlaying.Wpf/NowPlaying.Wpf.csproj
> +  </ItemGroup>
и это

2020-05-12 11:00 UTC, moetelo approved these changes

2020-05-12 11:01 UTC, merged