CoverUrl
veselv2010/NowPlaying pull request #68
Opened 2020-05-06 11:51 UTC by veselv2010

2020-05-06 11:51 UTC, veselv2010 commented
сын бляди ебаной этот гит придумал

2020-05-06 12:38 UTC, moetelo requested changes

2020-05-06 12:38 UTC, Shifu462 commented on NowPlaying.Core/Api/SpotifyRequestsManager.cs
> +            string coverUrl = (string)albumCover["images"][0].SelectToken("url");
`string coverUrl = (string)albumCover["images"][0]["url"];` ?

2020-05-07 06:21 UTC, moetelo approved these changes

2020-05-07 08:29 UTC, merged