Авторизация
veselv2010/NowPlaying pull request #70
Opened 2020-05-12 11:08 UTC by veselv2010

2020-05-13 13:44 UTC, moetelo requested changes

2020-05-13 13:44 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +            spotify = new SpotifyRequestsManager("7633771350404368ac3e05c9cf73d187",
я бы оставил это присваивание в конструкторе

2020-05-13 13:58 UTC, veselv2010 commented on NowPlaying.Wpf/AppViewModel.cs
> +            spotify = new SpotifyRequestsManager("7633771350404368ac3e05c9cf73d187",
метод об инициализации

2020-05-14 08:35 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/Header/HeaderBlock.xaml.cs
> +                ToggleTheme.OneWayBind(ToggleTheme.ViewModel,
чётко

2020-05-14 08:35 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/NpcWorkSwitch.xaml.cs
> +            NpcToggle.WhenActivated(d =>
чётко

2020-05-14 08:36 UTC, Shifu462 commented on NowPlaying.Wpf/App.config
>    </runtime>
этот файл можно было не обижать на самом деле

2020-05-14 08:37 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +            spotify = new SpotifyRequestsManager("7633771350404368ac3e05c9cf73d187",
как хочешь

2020-05-14 08:39 UTC, moetelo requested changes

2020-05-14 08:39 UTC, Shifu462 commented on NowPlaying.Wpf/Auth/AuthWindow.xaml.cs
> +            Dispatcher.Invoke(() => currentUrl = BrowserControl.Address);
а есть варик без диспетчера в этом контроле как-то обойтись?
насколько я помню это костыль против отсутствия мввм был

2020-05-14 08:57 UTC, veselv2010 commented on NowPlaying.Wpf/Auth/AuthWindow.xaml.cs
> +            Dispatcher.Invoke(() => currentUrl = BrowserControl.Address);
цеф в не в одном потоке с основным юи работает, по этой же причине в Dispose та же конструкция

2020-05-14 09:02 UTC, veselv2010 commented on NowPlaying.Wpf/App.config
>    </runtime>
в последний раз

2020-05-14 09:16 UTC, moetelo requested changes

2020-05-14 09:16 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +        private async Task SpotifyRequestInitialize()
А какой смысл того что ты извлёк отдельный метод?
В конструкторе ты же тоже его не эвэйтишь.

Ты можешь сделать этот метод публичным и вызвать из `MainWindow_OnLoaded`? Или завязаться на ещё какой-нибудь другой ивент, который происходит раньше по пайплайну впфа

2020-05-14 09:16 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +        private async Task SpotifyRequestInitialize()
Ты можешь убрать этот метод, вернуть присваивание `spotify = new Spotify(...)` в конструктор
А из `MainWindow_OnLoaded` (или, опять же, из другого ивента) дёрнуть `spotify.StartTokenRequests(..)`. Будет супер!

2020-05-14 09:20 UTC, veselv2010 commented on NowPlaying.Wpf/AppViewModel.cs
> +        private async Task SpotifyRequestInitialize()
звучит справедливо

2020-05-14 09:29 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +        private string GetCode()
не совсем `Get`
может `Ask`? или как нибудь ещё

2020-05-15 14:47 UTC, moetelo requested changes

2020-05-15 14:47 UTC, Shifu462 commented on NowPlaying.Core/Api/SpotifyRequestsManager.cs
> +    public sealed class SpotifyRequestsManager : RequestsManager, IDisposable
тут не нужно писать `IDisposable`

2020-05-15 14:47 UTC, Shifu462 commented on NowPlaying.Core/Api/SpotifyRequestsManager.cs
> +                throw new System.Exception();
https://stackoverflow.com/a/15496102/5512932

2020-05-15 14:50 UTC, moetelo approved these changes

2020-05-15 14:52 UTC, merged