Issue #71: README.md
veselv2010/NowPlaying pull request #72
Opened 2020-05-12 12:46 UTC by veselv2010

2020-05-12 13:26 UTC, moetelo requested changes

2020-05-12 13:26 UTC, Shifu462 commented on README.md
> +7. Paste console string into the csgo console (~) (exec "%assignedkey%" "exec audio.cfg")
`bind`

2020-05-12 13:26 UTC, Shifu462 commented on README.md
> +8. Press the assigned key to send current track info or use the autosend option metioned in the 4th step
me `n` tioned

2020-05-12 13:47 UTC, veselv2010 commented on README.md
> +8. Press the assigned key to send current track info or use the autosend option metioned in the 4th step
почему так, я же с мастера скопировал его, там пофикшенная версия

2020-05-12 15:21 UTC, Shifu462 commented on README.md
> +8. Press the assigned key to send current track info or use the autosend option metioned in the 4th step
фиксил ридми через браузер
а на комп себе ридми не подгрузил новый

```
git checkout master
git pull --rebase
```

2020-05-15 17:35 UTC, moetelo approved these changes

2020-05-15 17:46 UTC, merged