CurrentKeyControl
veselv2010/NowPlaying pull request #73
Opened 2020-05-15 17:47 UTC by veselv2010

2020-05-16 09:37 UTC, moetelo requested changes

2020-05-16 09:37 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/Controls/CurrentKeyControl.xaml.cs
> +            InitializeComponent();
трейлинг пробел нафигачил зачем

2020-05-16 09:37 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/Controls/CurrentKeyControl.xaml.cs
> +            MessageBox.Show("keydown fired");
может убрать этот месседжбокс? я так понимаю он для дебага был

2020-05-16 09:37 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +        [Reactive] public CurrentKeyControlViewModel CurrentKeyVM { get; set; } = new CurrentKeyControlViewModel();
может `CurrentKeyVM => CurrentKey` просто?

2020-05-16 09:37 UTC, Shifu462 commented on NowPlaying.Cli/Program.cs
> +            Console.WriteLine("Press bind button");
`the bind key`?

2020-05-16 09:38 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/Controls/CurrentKeyControl.xaml.cs
> +            InitializeComponent();
@veselv2010 
включи в своём редакторе/иде чтобы он по дефолту кропал trailing whitespaces при `Ctrl+S`

2020-05-16 09:39 UTC, veselv2010 commented on NowPlaying.Wpf/Controls/UserSettings/Controls/CurrentKeyControl.xaml.cs
> +            MessageBox.Show("keydown fired");
запомни брат такую фразу все будет но не сразу

2020-05-16 09:39 UTC, veselv2010 commented on NowPlaying.Wpf/AppViewModel.cs
> +        [Reactive] public CurrentKeyControlViewModel CurrentKeyVM { get; set; } = new CurrentKeyControlViewModel();
я все не решил выносить каренткей в отдельную вьюмодель или нет

2020-05-16 09:40 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +        [Reactive] public CurrentKeyControlViewModel CurrentKeyVM { get; set; } = new CurrentKeyControlViewModel();
я думаю не стоит выносить
объяснить с ходу не смогу почему так

2020-05-16 09:41 UTC, Shifu462 commented on NowPlaying.Wpf/AppViewModel.cs
> +        [Reactive] public CurrentKeyControlViewModel CurrentKeyVM { get; set; } = new CurrentKeyControlViewModel();
короче, если бы у тебя был обычный текстбокс, то ты бы в него передал вьюмодель стринг
 
а здесь всего лишь немного кастомный текстбокс с фичей конвертации в сурс-кей

2020-05-16 09:43 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/Controls/CurrentKeyControl.xaml.cs
> +            MessageBox.Show("keydown fired");
точно, пр же в драфте...

2020-05-17 11:26 UTC, Shifu462 commented on NowPlaying.Cli/Program.cs
> +            Console.WriteLine("Press bind button");
`key`?

2020-05-17 13:06 UTC, moetelo requested changes

2020-05-17 13:06 UTC, Shifu462 commented on NowPlaying.Core/InputSender/InputSenderWindows.cs
> +        private readonly Dictionary<ushort, ScanCodeShort> KeyValuePairs = new Dictionary<ushort, ScanCodeShort>
заодно `IDictionary` напиши здесь

2020-05-17 13:47 UTC, veselv2010 commented on NowPlaying.Core/InputSender/InputSenderWindows.cs
> +            {33, ScanCodeShort.UP}, //
слешем выделены клавиши, в работе которых я не уверен

2020-05-18 06:17 UTC, Shifu462 commented on NowPlaying.Core/InputSender/InputSenderWindows.cs
> +            {33, ScanCodeShort.UP}, //
а как проверить, работают они или нет?

2020-05-18 06:32 UTC, moetelo requested changes

2020-05-18 06:32 UTC, Shifu462 commented on NowPlaying.Cli/Program.cs
> +            string lastTrackId = string.Empty;
почему не `null`?

2020-05-18 06:32 UTC, Shifu462 commented on NowPlaying.Cli/Program.cs
> +            string lastTrackId = string.Empty;
вот в джаваскрипте есть `undefined` и `null` 
`undefined` используется когда значение ещё не было задано, а `null` — когда значение намеренно и осознанно установлено пустым
наверное, у тебя тут какой-то такой случай, ты внизу сравниваешь `track.Id` с этим говном или типа того....

2020-05-18 06:32 UTC, Shifu462 commented on NowPlaying.Core/InputSender/KeyFormatterWindows.cs
> +            return "key not found";
![image](https://user-images.githubusercontent.com/17011936/82180328-fe081a80-98e8-11ea-8a35-26f87c9f7e57.png)

2020-05-18 06:32 UTC, Shifu462 commented on NowPlaying.Core/InputSender/KeyFormatterWindows.cs
> +            return "key not found";
автоматический бан за эту хуйню
верни здесь налл пожалуйста

2020-05-18 06:32 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/UserSettingsBlockViewModel.cs
> +        [Reactive] public string CurrentSourceKey { get; set; }
я упустил что-то, в каком коммите ты `Theme` унёс в `UserSettingsBlockViewModel`, и заметил это только сейчас, извини.
 
здесь возникает большая путаница: ты увидел слово `Theme`, подумал, что это пользовательская настройка и унёс в `UserSettingsBlockViewModel`. ну юзерсеттинг же? юзерсеттинг.

но нет, всё на самом деле не так.
этот `Theme` вообще хуй пойми где нажмается (наверху окошка).
и более того, этот класс `UserSettingsBlockViewModel` не выполняет цели ХРАНЕНИЯ пользовательских настроек вообще.
 
какую же цель он выполняет? этот класс просто хранит в себе состояние контрола `UserSettingsBlock`. 
разве `Theme` есть в `UserSettings`? неа.

2020-05-18 06:32 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/UserSettingsBlockViewModel.cs
> +        [Reactive] public string CurrentSourceKey { get; set; }
будем честны: `HeaderBlockViewModel` хранит в себе то состояние, в котором же и должно быть свойство `Theme`.
кнопка переключатель темы в `HeaderBlock`? значит и тема `Theme` должна быть во вьюмодели `HeaderBlock`а.

2020-05-18 06:34 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/UserSettingsBlockViewModel.cs
> +        [Reactive] public string CurrentSourceKey { get; set; }
(к десятой строчке с `CurrentSourceKey` претензий не имею, если что)

2020-05-18 06:38 UTC, veselv2010 commented on NowPlaying.Core/InputSender/InputSenderWindows.cs
> +            {33, ScanCodeShort.UP}, //
сделать бинд на эту кнопку и посмотреть, работает ли автоматическая отправка

2020-05-18 06:38 UTC, Shifu462 commented on NowPlaying.Wpf/Controls/UserSettings/UserSettingsBlockViewModel.cs
> +        [Reactive] public string CurrentSourceKey { get; set; }
договорились: 
проперти `Theme` здесь не используется, её нужно удалить

2020-05-18 06:39 UTC, veselv2010 commented on NowPlaying.Core/InputSender/InputSenderWindows.cs
> +            {33, ScanCodeShort.UP}, //
либо через винапи GetLastError смотреть код ошибки

2020-05-18 07:19 UTC, moetelo approved these changes

2020-05-18 07:21 UTC, merged